Repository celestiaorg/node-rpc-docs, pull requests merged in 2024-06, with the labels that each got.

#46 fix: remove surrounding square brackets from response examples
  src/pages/index.tsx
Labels: bug

#47 feat: add v0.13.6 and v0.13.7
  public/specs/openrpc-v0.13.6.json
  public/specs/openrpc-v0.13.7.json
  src/pages/index.tsx
Labels: documentation

#51 feat: add backlinks to tutorials
  src/pages/index.tsx
Labels: documentation, enhancement
